import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import express from 'express';
import helmet from 'helmet';
import { rateLimit } from 'express-rate-limit';
import dotenv from 'dotenv';
import { dbEnabled, initDatabase, query, closeDatabase } from './db.js';

dotenv.config();
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);
const app=express();const port=Number(process.env.PORT||10000);const GEMINI_MODEL=String(process.env.GEMINI_MODEL||'gemini-3.8-flash').trim();
app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(express.json({limit:'1mb'}));app.use('/api/',rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-8',legacyHeaders:false}));

const memory={
 guardian:{id:1,role:'guardian',name:'보호자',linked_profile_id:2},user:{id:2,role:'user',name:'사용자',linked_profile_id:1},
 settings:{profile_id:2,grid_size:4,voice_type:'CHILD_MALE',speech_rate:1.0,language_level:2},
 symbols:[['추천','좋아요','👍','#82D8E9'],['추천','싫어요','✖','#82D8E9'],['추천','슬퍼요','😢','#82D8E9'],['추천','기뻐요','😊','#82D8E9'],['음식','덥다','🥵','#82D8E9'],['음식','배','🍚','#FFDD83'],['대화','그리고','➕','#C3CDC9'],['대화','안녕','👋','#8089FF'],['행동','달려요','🏃','#E5F1F8'],['행동','가다','➡️','#E6F8F0'],['음식','먹다','🍴','#E4F8EF'],['음식','물','🥤','#FFF1CB'],['사람','가다','🚶','#E8F6EE'],['사람','엄마','👩','#FFE8DA'],['긴급어','아파요','🤕','#FFE7E8'],['긴급어','화장실','🚻','#FFF0C9']].map((x,i)=>({id:i+1,profile_id:2,category:x[0],label:x[1],emoji:x[2],color:x[3],image_data:'',favorite:[7,11,13].includes(i),emergency:i>=14,sort_order:i})),
 routines:[{id:1,time_text:'08:00',repeat_type:'매일',sentence:'등교 준비 — 학교 상징 우선',enabled:true},{id:2,time_text:'12:30',repeat_type:'매일',sentence:'점심 약 복용 알림 팝업',enabled:true},{id:3,time_text:'21:00',repeat_type:'매일',sentence:'취침 루틴 — 양치, 약, 졸려요',enabled:false}],
 pairings:new Map(),usage:[]
};
async function getIds(){if(!dbEnabled)return{guardianId:1,userId:2};const r=await query("SELECT id,role FROM malmoa_profiles WHERE role IN ('guardian','user') ORDER BY id");return{guardianId:r.rows.find(x=>x.role==='guardian')?.id,userId:r.rows.find(x=>x.role==='user')?.id}}
app.get('/api/health',(_req,res)=>res.json({ok:true,app:'malmoa',database:dbEnabled?'configured':'memory'}));
app.get('/api/malmoa/bootstrap',async(_req,res,next)=>{try{if(!dbEnabled)return res.json({guardian:memory.guardian,user:memory.user,settings:memory.settings,symbols:memory.symbols,routines:memory.routines});const{guardianId,userId}=await getIds();const[guardian,user,settings,symbols,routines]=await Promise.all([query('SELECT * FROM malmoa_profiles WHERE id=$1',[guardianId]),query('SELECT * FROM malmoa_profiles WHERE id=$1',[userId]),query('SELECT * FROM malmoa_settings WHERE profile_id=$1',[userId]),query('SELECT * FROM malmoa_symbols WHERE profile_id=$1 ORDER BY sort_order,id',[userId]),query('SELECT * FROM malmoa_routines WHERE guardian_profile_id=$1 ORDER BY time_text,id',[guardianId])]);res.json({guardian:guardian.rows[0],user:user.rows[0],settings:settings.rows[0],symbols:symbols.rows,routines:routines.rows})}catch(e){next(e)}});
app.patch('/api/malmoa/settings',async(req,res,next)=>{try{const grid=[2,3,4].includes(Number(req.body.grid_size))?Number(req.body.grid_size):undefined;const voice=['CHILD_MALE','CHILD_FEMALE','ADULT_FEMALE','ADULT_MALE'].includes(req.body.voice_type)?req.body.voice_type:undefined;const rate=Math.max(.7,Math.min(1.3,Number(req.body.speech_rate||1)));const level=Math.max(1,Math.min(4,Number(req.body.language_level||2)));if(!dbEnabled){if(grid)memory.settings.grid_size=grid;if(voice)memory.settings.voice_type=voice;memory.settings.speech_rate=rate;memory.settings.language_level=level;return res.json(memory.settings)}const{userId}=await getIds();const cur=await query('SELECT * FROM malmoa_settings WHERE profile_id=$1',[userId]);const row=cur.rows[0]||{};const r=await query('UPDATE malmoa_settings SET grid_size=$2,voice_type=$3,speech_rate=$4,language_level=$5,updated_at=NOW() WHERE profile_id=$1 RETURNING *',[userId,grid??row.grid_size,voice??row.voice_type,rate,level]);res.json(r.rows[0])}catch(e){next(e)}});

function symbolPayload(body={}){const p={};if(typeof body.label==='string'&&body.label.trim())p.label=body.label.trim().slice(0,60);if(typeof body.category==='string'&&body.category.trim())p.category=body.category.trim().slice(0,30);if(typeof body.emoji==='string'&&body.emoji.trim())p.emoji=body.emoji.trim().slice(0,16);if(typeof body.color==='string'&&/^#[0-9A-Fa-f]{6}$/.test(body.color))p.color=body.color;if('favorite'in body)p.favorite=Boolean(body.favorite);if('emergency'in body)p.emergency=Boolean(body.emergency);if('image_data'in body){const image=String(body.image_data||'');if(!image||(image.length<=450000&&/^data:image\/(?:png|jpeg|webp);base64,/i.test(image)))p.image_data=image}return p}
app.post('/api/malmoa/symbols',async(req,res,next)=>{try{const p=symbolPayload(req.body);if(!p.label)return res.status(400).json({error:'LABEL_REQUIRED'});p.category=p.category||'추천';p.emoji=p.emoji||'💬';p.color=p.color||'#86D8EA';p.image_data=p.image_data||'';p.favorite=Boolean(p.favorite);p.emergency=Boolean(p.emergency);if(!dbEnabled){const id=Math.max(0,...memory.symbols.map(x=>Number(x.id)||0))+1;const item={id,profile_id:2,sort_order:memory.symbols.length,...p};memory.symbols.push(item);return res.json(item)}const{userId}=await getIds();const r=await query('INSERT INTO malmoa_symbols(profile_id,category,label,emoji,color,image_data,favorite,emergency,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,(SELECT COALESCE(MAX(sort_order),-1)+1 FROM malmoa_symbols WHERE profile_id=$1)) RETURNING *',[userId,p.category,p.label,p.emoji,p.color,p.image_data,p.favorite,p.emergency]);res.json(r.rows[0])}catch(e){next(e)}});
app.patch('/api/malmoa/symbols/:id',async(req,res,next)=>{try{const id=Number(req.params.id),p=symbolPayload(req.body),hasImage=Object.prototype.hasOwnProperty.call(p,'image_data');if(!dbEnabled){const item=memory.symbols.find(x=>Number(x.id)===id);if(!item)return res.status(404).json({error:'NOT_FOUND'});Object.assign(item,p);return res.json(item)}const r=await query(`UPDATE malmoa_symbols SET label=COALESCE($2,label),category=COALESCE($3,category),emoji=COALESCE($4,emoji),color=COALESCE($5,color),favorite=COALESCE($6,favorite),emergency=COALESCE($7,emergency),image_data=CASE WHEN $8 THEN $9 ELSE image_data END WHERE id=$1 RETURNING *`,[id,p.label??null,p.category??null,p.emoji??null,p.color??null,'favorite'in p?p.favorite:null,'emergency'in p?p.emergency:null,hasImage,p.image_data??'']);if(!r.rows[0])return res.status(404).json({error:'NOT_FOUND'});res.json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/malmoa/symbols/:id',async(req,res,next)=>{try{const id=Number(req.params.id);if(!dbEnabled){const before=memory.symbols.length;memory.symbols=memory.symbols.filter(x=>Number(x.id)!==id);if(before===memory.symbols.length)return res.status(404).json({error:'NOT_FOUND'});return res.json({ok:true})}const r=await query('DELETE FROM malmoa_symbols WHERE id=$1 RETURNING id',[id]);if(!r.rows[0])return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true})}catch(e){next(e)}});

app.post('/api/malmoa/pairings',async(_req,res,next)=>{try{const code=String(crypto.randomInt(0,1000000)).padStart(6,'0');const expiresAt=new Date(Date.now()+10*60*1000);if(!dbEnabled){memory.pairings.set(code,{code,expires_at:expiresAt.toISOString(),claimed_at:null});return res.json({code,expires_at:expiresAt.toISOString()})}const{guardianId}=await getIds();const r=await query('INSERT INTO malmoa_pairings(guardian_profile_id,code,expires_at) VALUES($1,$2,$3) RETURNING code,expires_at',[guardianId,code,expiresAt]);res.json(r.rows[0])}catch(e){next(e)}});
app.get('/api/malmoa/pairings/:code',async(req,res,next)=>{try{const code=String(req.params.code||'').replace(/\D/g,'').slice(0,6);if(code.length!==6)return res.status(400).json({error:'INVALID_CODE'});if(!dbEnabled){const p=memory.pairings.get(code);if(!p)return res.status(404).json({error:'NOT_FOUND'});return res.json({code,expires_at:p.expires_at,claimed:Boolean(p.claimed_at),expired:new Date(p.expires_at)<=new Date()})}const r=await query('SELECT code,expires_at,claimed_at FROM malmoa_pairings WHERE code=$1',[code]);if(!r.rows[0])return res.status(404).json({error:'NOT_FOUND'});res.json({code:r.rows[0].code,expires_at:r.rows[0].expires_at,claimed:Boolean(r.rows[0].claimed_at),expired:new Date(r.rows[0].expires_at)<=new Date()})}catch(e){next(e)}});
app.post('/api/malmoa/pairings/claim',async(req,res,next)=>{try{const code=String(req.body.code||'').replace(/\D/g,'').slice(0,6);if(code.length!==6)return res.status(400).json({error:'INVALID_CODE'});if(!dbEnabled){const p=memory.pairings.get(code);if(!p||new Date(p.expires_at)<new Date()||p.claimed_at)return res.status(400).json({error:'INVALID_OR_EXPIRED'});p.claimed_at=new Date().toISOString();return res.json({ok:true,user_profile_id:2})}const{userId}=await getIds();const r=await query('UPDATE malmoa_pairings SET user_profile_id=$2,claimed_at=NOW() WHERE code=$1 AND expires_at>NOW() AND claimed_at IS NULL RETURNING *',[code,userId]);if(!r.rows[0])return res.status(400).json({error:'INVALID_OR_EXPIRED'});res.json({ok:true,user_profile_id:userId})}catch(e){next(e)}});

app.post('/api/malmoa/routines',async(req,res,next)=>{try{const time=/^\d{2}:\d{2}$/.test(String(req.body.time_text||''))?String(req.body.time_text):'09:00';const repeat=String(req.body.repeat_type||'매일').slice(0,20);const sentence=String(req.body.sentence||'').trim().slice(0,180);if(!sentence)return res.status(400).json({error:'SENTENCE_REQUIRED'});const enabled=req.body.enabled!==false;if(!dbEnabled){const id=Math.max(0,...memory.routines.map(x=>Number(x.id)||0))+1;const item={id,time_text:time,repeat_type:repeat,sentence,enabled};memory.routines.push(item);return res.json(item)}const{guardianId}=await getIds();const r=await query('INSERT INTO malmoa_routines(guardian_profile_id,time_text,repeat_type,sentence,enabled) VALUES($1,$2,$3,$4,$5) RETURNING *',[guardianId,time,repeat,sentence,enabled]);res.json(r.rows[0])}catch(e){next(e)}});
app.patch('/api/malmoa/routines/:id',async(req,res,next)=>{try{const id=Number(req.params.id);if(!dbEnabled){const item=memory.routines.find(x=>Number(x.id)===id);if(!item)return res.status(404).json({error:'NOT_FOUND'});if('enabled'in req.body)item.enabled=Boolean(req.body.enabled);if(req.body.sentence)item.sentence=String(req.body.sentence).slice(0,180);return res.json(item)}const r=await query('UPDATE malmoa_routines SET enabled=COALESCE($2,enabled),sentence=COALESCE($3,sentence) WHERE id=$1 RETURNING *',[id,'enabled'in req.body?Boolean(req.body.enabled):null,req.body.sentence?String(req.body.sentence).slice(0,180):null]);if(!r.rows[0])return res.status(404).json({error:'NOT_FOUND'});res.json(r.rows[0])}catch(e){next(e)}});
app.delete('/api/malmoa/routines/:id',async(req,res,next)=>{try{const id=Number(req.params.id);if(!dbEnabled){const before=memory.routines.length;memory.routines=memory.routines.filter(x=>Number(x.id)!==id);if(before===memory.routines.length)return res.status(404).json({error:'NOT_FOUND'});return res.json({ok:true})}const r=await query('DELETE FROM malmoa_routines WHERE id=$1 RETURNING id',[id]);if(!r.rows[0])return res.status(404).json({error:'NOT_FOUND'});res.json({ok:true})}catch(e){next(e)}});

app.post('/api/malmoa/usage',async(req,res,next)=>{try{const utterance=String(req.body.utterance||'').trim().slice(0,300);if(!utterance)return res.status(400).json({error:'EMPTY'});const emergency=Boolean(req.body.emergency),source=String(req.body.source||'symbol').slice(0,30);if(!dbEnabled){memory.usage.unshift({id:memory.usage.length+1,utterance,emergency,source,created_at:new Date().toISOString()});return res.json({ok:true})}const{userId}=await getIds();await query('INSERT INTO malmoa_usage_logs(user_profile_id,utterance,source,emergency) VALUES($1,$2,$3,$4)',[userId,utterance,source,emergency]);res.json({ok:true})}catch(e){next(e)}});
app.get('/api/malmoa/usage',async(_req,res,next)=>{try{if(!dbEnabled)return res.json(memory.usage.slice(0,100));const{userId}=await getIds();const r=await query('SELECT * FROM malmoa_usage_logs WHERE user_profile_id=$1 ORDER BY created_at DESC LIMIT 100',[userId]);res.json(r.rows)}catch(e){next(e)}});
app.post('/api/malmoa/ai',async(req,res,next)=>{try{const words=Array.isArray(req.body.words)?req.body.words.map(v=>String(v).trim()).filter(Boolean).slice(0,8):[];if(!words.length)return res.status(400).json({error:'EMPTY_WORDS'});const level=Math.max(1,Math.min(4,Number(req.body.level||2)));const fallback=level===1?words[0]:`${words.join(' ')} 주세요.`.replace(/\s+/g,' ').trim();const apiKey=String(process.env.GEMINI_API_KEY||'').trim();if(!apiKey)return res.json({text:fallback,source:'fallback'});const guide={1:'한 단어 또는 1어절',2:'2~4어절의 아주 짧은 문장',3:'5~6어절의 일반 문장',4:'7어절 이상의 자연스러운 문장'}[level];const prompt=`AAC 사용자가 고른 단어: ${words.join(', ')}. 의미를 새로 만들지 말고 한국어 문장 하나로 정리해라. 사용자가 이해하기 쉬운 ${guide} 수준으로 작성한다. 출력은 문장 하나만.`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(GEMINI_MODEL)}:generateContent?key=${encodeURIComponent(apiKey)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.35,maxOutputTokens:120}}),signal:controller.signal});const data=await r.json();const text=data?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim();res.json({text:text||fallback,source:text?'gemini':'fallback'})}finally{clearTimeout(timer)}}catch(e){next(e)}});

app.use(express.static(path.join(__dirname,'public'),{extensions:['html']}));
app.get('/guardian',(_req,res)=>res.sendFile(path.join(__dirname,'public','guardian.html')));
app.get('/settings',(_req,res)=>res.sendFile(path.join(__dirname,'public','settings.html')));
app.get('/report',(_req,res)=>res.sendFile(path.join(__dirname,'public','report.html')));
app.get('/user',(_req,res)=>res.sendFile(path.join(__dirname,'public','user.html')));
app.get('/connect',(_req,res)=>res.sendFile(path.join(__dirname,'public','connect.html')));
app.use((req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(path.join(__dirname,'public','index.html'))});
app.use((error,_req,res,_next)=>{console.error(error);res.status(error.status||500).json({error:error.message||'INTERNAL_ERROR'})});
let server;initDatabase().catch(e=>console.error('[database] init failed',e)).finally(()=>{server=app.listen(port,'0.0.0.0',()=>console.log(`[malmoa] listening on ${port}`))});
async function shutdown(){if(server)server.close();await closeDatabase();process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
